import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { ticket } = await req.json();
    
    if (!ticket || !ticket.legs) {
      return new Response(
        JSON.stringify({ error: 'Invalid ticket data' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const LOVABLE_API_KEY = Deno.env.get('LOVABLE_API_KEY');
    if (!LOVABLE_API_KEY) {
      throw new Error('LOVABLE_API_KEY not configured');
    }

    // Build structured data for each match
    const matchesData = ticket.legs.map((leg: any, index: number) => ({
      match_number: index + 1,
      teams: `${leg.home_team} vs ${leg.away_team}`,
      league: leg.league || 'Unknown League',
      kickoff: leg.kickoff || 'TBD',
      recommended_bet: `${leg.market} ${leg.pick}`,
      odds: leg.odds,
      bookmaker: leg.bookmaker,
      edge: leg.edge ? `+${(leg.edge * 100).toFixed(1)}%` : 'N/A',
      model_prob: leg.model_prob ? `${(leg.model_prob * 100).toFixed(1)}%` : 'N/A',
      book_prob: leg.book_prob ? `${(leg.book_prob * 100).toFixed(1)}%` : 'N/A',
      reason: leg.reason || 'Optimized bet based on statistical analysis'
    }));

    const ticketSummary = {
      total_odds: ticket.total_odds,
      estimated_win_prob: ticket.estimated_win_prob ? `${ticket.estimated_win_prob.toFixed(1)}%` : 'N/A',
      mode: ticket.mode,
      used_live: ticket.used_live || false,
      number_of_legs: ticket.legs.length
    };

    // Structured prompt for Gemini
    const prompt = `You are Gemini 2.5 Flash — an advanced AI sports analyst integrated into the BET AI system.

Your task: Analyze the following betting ticket that was generated by our Optimized Bets engine.

TICKET SUMMARY:
${JSON.stringify(ticketSummary, null, 2)}

MATCHES DATA:
${JSON.stringify(matchesData, null, 2)}

---

### 🎯 Your Objective:
Provide a detailed, expert-level analysis of the entire ticket.
For each match, explain **why the bet makes sense**, referring to the provided data and adding your own deeper contextual reasoning based on football knowledge.

**Important:**
- Never contradict the provided optimized bet. Your role is to justify and expand upon it.
- Use factual, professional language — like a sports analyst report.
- Focus on key factors such as team form, tactical matchups, and statistical trends.
- If possible, identify *supporting factors* (why the bet is strong) and *risk factors* (what could affect it).

---

### 🧩 Output Format:
Return a structured JSON with this format:
{
  "overall_summary": "General analysis of the entire ticket — e.g. overall logic, consistency, and confidence.",
  "matches": [
    {
      "match_title": "Team A vs Team B (League)",
      "recommended_bet": "Over 2.5 Goals @ 1.75",
      "analysis": "Detailed 3–5 sentence analysis explaining why this bet was generated and what factors support it. Mention form, key players, match context, etc.",
      "confidence_level": "High / Medium / Low"
    }
  ]
}

Generate the JSON response only — no extra commentary. Ensure it's valid JSON.`;

    console.log('[analyze-ticket] Calling Gemini 2.5 Flash...');

    const response = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${LOVABLE_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'google/gemini-2.5-flash',
        messages: [
          { role: 'user', content: prompt }
        ],
        temperature: 0.7,
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('[analyze-ticket] Gemini API error:', response.status, errorText);
      
      if (response.status === 429) {
        return new Response(
          JSON.stringify({ error: 'Rate limit exceeded. Please try again later.' }),
          { status: 429, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        );
      }
      
      throw new Error(`Gemini API error: ${response.status}`);
    }

    const data = await response.json();
    const geminiResponse = data.choices?.[0]?.message?.content;

    if (!geminiResponse) {
      throw new Error('No response from Gemini');
    }

    console.log('[analyze-ticket] Gemini response received');

    // Try to parse the JSON response
    let analysis;
    try {
      // Extract JSON from markdown code blocks if present
      const jsonMatch = geminiResponse.match(/```json\s*([\s\S]*?)\s*```/) || 
                       geminiResponse.match(/```\s*([\s\S]*?)\s*```/);
      const jsonText = jsonMatch ? jsonMatch[1] : geminiResponse;
      analysis = JSON.parse(jsonText);
    } catch (parseError) {
      console.error('[analyze-ticket] Failed to parse Gemini response:', geminiResponse);
      // Return a fallback structure
      analysis = {
        overall_summary: geminiResponse.substring(0, 500),
        matches: matchesData.map((m: any) => ({
          match_title: m.teams,
          recommended_bet: m.recommended_bet,
          analysis: 'Analysis unavailable in structured format.',
          confidence_level: 'Medium'
        }))
      };
    }

    return new Response(
      JSON.stringify({ analysis }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error) {
    console.error('[analyze-ticket] Error:', error);
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : 'Unknown error' }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
