-- Create performance_weights table for Bayesian-adjusted win rates
CREATE TABLE IF NOT EXISTS public.performance_weights (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  market   TEXT    NOT NULL,
  side     TEXT    NOT NULL,
  line     NUMERIC NOT NULL,
  league_id INTEGER, -- NULL = global (all leagues)

  -- Raw stats
  sample_size INTEGER NOT NULL DEFAULT 0,
  wins        INTEGER NOT NULL DEFAULT 0,
  losses      INTEGER NOT NULL DEFAULT 0,
  pushes      INTEGER NOT NULL DEFAULT 0,

  -- Calculated metrics
  raw_win_rate   NUMERIC NOT NULL DEFAULT 0,
  roi_pct        NUMERIC NOT NULL DEFAULT 0,
  bayes_win_rate NUMERIC NOT NULL DEFAULT 0,
  weight         NUMERIC NOT NULL DEFAULT 1.0,

  computed_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT performance_weights_valid_side
    CHECK (side IN ('over','under','yes','no','home','away','draw'))
);

-- IMPORTANT: enforce uniqueness even when league_id is NULL
CREATE UNIQUE INDEX IF NOT EXISTS performance_weights_unique_key
ON public.performance_weights (market, side, line, COALESCE(league_id, -1));

-- Lookup indexes
CREATE INDEX IF NOT EXISTS idx_performance_weights_lookup
ON public.performance_weights (market, side, line);

CREATE INDEX IF NOT EXISTS idx_performance_weights_league
ON public.performance_weights (league_id);

-- RLS
ALTER TABLE public.performance_weights ENABLE ROW LEVEL SECURITY;

-- Read access for authenticated users
CREATE POLICY "Anyone can read performance weights"
ON public.performance_weights
FOR SELECT
TO authenticated
USING (true);

-- Service role full access (JWT claim)
CREATE POLICY "Service role full access (performance_weights)"
ON public.performance_weights
FOR ALL
USING (auth.role() = 'service_role')
WITH CHECK (auth.role() = 'service_role');