-- ===========================================================================
-- Structural fixture used ONLY to prove supabase/staging/seed_staging_integration.sql
-- is valid and idempotent against the real column definitions of the tables it
-- touches. Column names, types, nullability, defaults and unique keys mirror
-- the production catalogue exactly (verified by introspection, RC3.4).
-- It is NOT a baseline and must never be applied to any real project.
-- ===========================================================================
CREATE SCHEMA IF NOT EXISTS auth;

CREATE TABLE auth.users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email text UNIQUE
);

CREATE TABLE public.countries (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  flag text,
  code text,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT countries_code_uk UNIQUE (code)
);

CREATE TABLE public.leagues (
  id integer PRIMARY KEY,
  name text NOT NULL,
  country_id integer,
  season integer NOT NULL,
  logo text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE public.fixtures (
  id bigint PRIMARY KEY,
  league_id integer,
  date date NOT NULL,
  "timestamp" bigint,
  teams_home jsonb NOT NULL,
  teams_away jsonb NOT NULL,
  status text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  original_kickoff_at timestamptz,
  last_rescheduled_at timestamptz
);

CREATE TABLE public.generated_tickets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  total_odds numeric NOT NULL,
  min_target numeric NOT NULL,
  max_target numeric NOT NULL,
  used_live boolean NOT NULL DEFAULT false,
  legs jsonb NOT NULL,
  created_at timestamptz DEFAULT now(),
  user_id uuid NOT NULL,
  ticket_mode text,
  ticket_model_prob numeric
);

CREATE TABLE public.ticket_outcomes (
  ticket_id uuid PRIMARY KEY,
  user_id uuid NOT NULL,
  legs_total integer NOT NULL DEFAULT 0,
  legs_settled integer NOT NULL DEFAULT 0,
  legs_won integer NOT NULL DEFAULT 0,
  legs_lost integer NOT NULL DEFAULT 0,
  legs_pushed integer NOT NULL DEFAULT 0,
  legs_void integer NOT NULL DEFAULT 0,
  ticket_status text NOT NULL DEFAULT 'PENDING',
  total_odds numeric NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  settled_at timestamptz,
  ticket_mode text,
  ticket_model_prob numeric
);

CREATE TABLE public.ticket_leg_outcomes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id uuid NOT NULL,
  user_id uuid NOT NULL,
  fixture_id bigint NOT NULL,
  league_id integer,
  market text NOT NULL,
  side text NOT NULL,
  line numeric NOT NULL,
  odds numeric NOT NULL,
  selection_key text NOT NULL,
  selection text NOT NULL,
  source text NOT NULL DEFAULT 'prematch',
  picked_at timestamptz NOT NULL DEFAULT now(),
  kickoff_at timestamptz,
  settled_at timestamptz,
  result_status text NOT NULL DEFAULT 'PENDING',
  actual_value numeric,
  scored_version text DEFAULT 'v1',
  derived_from_selection boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  model_prob numeric,
  score_claim_token uuid,
  score_claimed_at timestamptz,
  score_attempts integer NOT NULL DEFAULT 0,
  kickoff_drift_seconds bigint,
  settlement_hold_reason text,
  settlement_held_at timestamptz,
  settlement_policy_version text,
  home_team_id_snapshot bigint,
  away_team_id_snapshot bigint
);

CREATE TABLE public.market_coins (
  user_id uuid PRIMARY KEY,
  balance integer NOT NULL DEFAULT 1000,
  total_wagered integer NOT NULL DEFAULT 0,
  total_won integer NOT NULL DEFAULT 0,
  total_fees_paid integer NOT NULL DEFAULT 0,
  last_reset_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.prediction_markets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  category text NOT NULL DEFAULT 'football',
  market_type text NOT NULL DEFAULT 'binary',
  status text NOT NULL DEFAULT 'draft',
  odds_yes numeric NOT NULL,
  odds_no numeric NOT NULL,
  total_staked_yes integer NOT NULL DEFAULT 0,
  total_staked_no integer NOT NULL DEFAULT 0,
  fixture_id bigint,
  closes_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO auth.users (email) VALUES
  ('staging-user-a@ticketai.test'),
  ('staging-user-b@ticketai.test');
